### ISSUE TITLE
Should we add a small database?

### ISSUE THREAD

**Issue by frostyandy2k** [ScaleIT-Org/ionic-app-skeleton#1]
* Or maybe a postgre? or should we create a new repo where we show how we can add a database container?
* Should add a database provider or just as documentation?

**Comment by fridaypatrick** [comment]
This is a **backend** feature. Frontend should be restricted to only read from backend or from a local JSON file (to load examples). 

The only thing the frontend should do for this case is to declare a service which queries data from a server, like the `HttpDataProvider ` in this repo.
