### ISSUE TITLE
Windows docker compose version too old

### ISSUE THREAD

**Issue by RobinFischer** [ScaleIT-Org/ionic-app-skeleton#17]
Seems it's an issue with Windows, switch to linux containers until fixed by docker

https://github.com/docker/compose/issues/4106

c:\Users\robin\Documents\GitHub\ionic-app-skeleton>docker-compose up
ERROR: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```

c:\Users\robin\Documents\GitHub\ionic-app-skeleton>
c:\Users\robin\Documents\GitHub\ionic-app-skeleton>docker --version
Docker version 18.03.0-ce, build 0520e24

c:\Users\robin\Documents\GitHub\ionic-app-skeleton>docker-compose version
docker-compose version 1.20.1, build 5d8c71b2
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```

**Comment by fridaypatrick** [comment]
I guess this is rather an issue with docker compose than with the skeleton. You should upgrade your local "docker for windows" version to fix this.

Be also aware that the base image is linux and cannot be used when windows containers are chosen in docker for windows.

Closing this issue for now.
